databases:
  - name: talentrag-db
    plan: free
    databaseName: talentrag_db
    user: talentrag

services:
  - type: web
    plan: free
    name: talentrag-backend
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn backend.wsgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: talentrag-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: OPENAI_API_KEY
        sync: false
